"""initial schema

Revision ID: adfff152c215
Revises: 
Create Date: 2026-06-10 09:50:30.554131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfff152c215'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('bug_type', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('behavior_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('avg_hints_needed', sa.Float(), nullable=False),
    sa.Column('forms_hypothesis_rate', sa.Float(), nullable=False),
    sa.Column('reads_error_first_rate', sa.Float(), nullable=False),
    sa.Column('sessions_evaluated', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('debug_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bug_type', sa.String(length=100), nullable=True),
    sa.Column('sub_skill_tested', sa.String(length=100), nullable=True),
    sa.Column('hints_given', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('sub_skill', sa.String(length=100), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('times_encountered', sa.Integer(), nullable=False),
    sa.Column('times_struggled', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept', 'sub_skill')
    )
    op.create_table('sm2_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('next_review_at', sa.Date(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_quality', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept')
    )
    op.create_table('struggle_map',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bug_type', sa.String(length=100), nullable=False),
    sa.Column('sub_skill', sa.String(length=100), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_eventually', sa.Boolean(), nullable=False),
    sa.Column('hints_needed_last', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['debug_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_messages')
    op.drop_table('struggle_map')
    op.drop_table('sm2_schedules')
    op.drop_table('knowledge_states')
    op.drop_table('debug_sessions')
    op.drop_table('behavior_patterns')
    op.drop_table('users')
    op.drop_table('content_items')
    # ### end Alembic commands ###
